-- SEED — Forfaits LPP perfusion + nutrition (PERFADOM / NEAD / NPAD)
-- Extrait de GRILLEST.pdf (LPPR maj 03-06-2026). a_verifier=true : À VALIDER.
-- À exécuter après 0081 + 0085 (colonne famille).
insert into public.lpp (code, libelle, prix_ttc, periodicite, famille, a_verifier) values
  ('1100850', 'nutrition parentérale — Nutrition parentérale, sans entérale associée, pompe, prest° hebd., après 12 prem. Sem. Forfait de prestat', 70.00, 'hebdomadaire', 'npad', true),
  ('1101648', 'perfusion — Perf a dom, forf heb consom-access, diffuseur, 2a3perf/ s, PERFADOM35-C-DIFF = 2A3/ S. Forfait hebdomadaire de consomm', null, 'hebdomadaire', 'perfusion', true),
  ('1102270', 'perfusion — Perf à dom, forf hebdo consom-access, diffuseur, 3 perf/ j, PERFADOM39-C-DIFF = 3/ J. Forfait hebdomadaire de consomma', null, 'hebdomadaire', 'perfusion', true),
  ('1103392', 'perfusion — Perfusion à dom, forf d''entret voie centrale, PERFADOM21-ENTRETIEN-VC-SF-PICC. Forfait de consommables et d''accessoire', 9.16, 'unitaire', 'perfusion', true),
  ('1103647', 'perfusion — Perf à dom, forf heb consom-access, diffuseur, 1perf/ S, PERFADOM43-C-DIFF IMMU-SC. Forfait hebdomadaire de consommabl', null, 'hebdomadaire', 'perfusion', true),
  ('1107250', 'perfusion — Perf a dom, forf heb consom-access, diffuseur, 4a6perf/ s, PERFADOM36-C-DIFF = 4A6/ S. Forfait hebdomadaire de consomm', 144.66, 'hebdomadaire', 'perfusion', true),
  ('1111902', 'nutrition entérale — Nutrition entérale, forfait hebdomadaire sans pompe ou par gravité : Forfait 1, sans pompe ou par gravité : I', 60.39, 'hebdomadaire', 'nead', true),
  ('1120261', 'perfusion — Perf à dom, forf consom-access, diffuseur, 1perf/ j, PERFADOM44-C-DIFF IMMU-IV. Forfait journalier de consommables et', 44.35, 'journalier', 'perfusion', true),
  ('1120522', 'nutrition parentérale — Nutrition parentérale, forfait d’installation après perfusion à domicile. Le forfait d’installation de nut', 173.54, 'installation', 'npad', true),
  ('1121326', 'perfusion — Perf à dom, forf hebdo consom-access, Gravité, 1 perf/ j, PERFADOM18-C-GRAV = 1/ J. Forfait hebdomadaire de consommabl', 76.02, 'hebdomadaire', 'perfusion', true),
  ('1122395', 'perfusion — Perf à dom, forf hebdo consom-access, diffuseur, > 3 perf/ j, PERFADOM40-C-DIFF > 3/ J. Forfait hebdomadaire de consom', null, 'hebdomadaire', 'perfusion', true),
  ('1126364', 'perfusion — Perf a dom, forf heb consom-access, système actif, 4a6perf/ s, PERFADOM29-C-SA = 4A6/ S. Forfait hebdomadaire de conso', null, 'hebdomadaire', 'perfusion', true),
  ('1130354', 'nutrition parentérale — Nutrition parentérale, forfait de première installation. Le forfait de première installation de nutrition', 390.00, 'installation', 'npad', true),
  ('1131030', 'perfusion — Perf à dom, forf hebdo consom-access, diffuseur, 2 perf/ j, PERFADOM38-C-DIFF = 2/ J. Forfait hebdomadaire de consomma', 409.47, 'hebdomadaire', 'perfusion', true),
  ('1131313', 'nutrition entérale — Nut entér, enfant 3-18 ans et adulte, GRAND FONTAINE, KETOVIE 4:1, 250 mL B/30. Denrée alimentaire destinée à', 224.61, 'hebdomadaire', 'nead', true),
  ('1134211', 'perfusion — Perf a dom, forf hebdo consom-access, système actif, 3 perf/ j, PERFADOM32-C-SA = 3/ J. Forfait hebdomadaire de consom', 665.23, 'hebdomadaire', 'perfusion', true),
  ('1136061', 'perfusion — Perf a dom, forf heb consom-access, système actif, 2a3perf/ s, PERFADOM28-C-SA = 2A3/ S. Forfait hebdomadaire de conso', 71.44, 'hebdomadaire', 'perfusion', true),
  ('1137095', 'perfusion — Perfusion à domicile, forfait transfusion, PERFADOM23-TRANSFUSION-de-PSL-en-EFS. Forfait de consommables et d''accessoi', 18.32, 'installation', 'perfusion', true),
  ('1143279', 'perfusion — Perf à dom, forf hebdo consom-access, Gravité, 2 perf/ j, PERFADOM19-C-GRAV = 2/ J. Forfait hebdomadaire de consommabl', 143.80, 'hebdomadaire', 'perfusion', true),
  ('1145410', 'nutrition parentérale — Nutrition parentérale < = 5 j/7, consommables et accessoires, npad, forfait. Pour chaque période entamée d', 115.00, 'hebdomadaire', 'npad', true),
  ('1149141', 'perfusion — Perf a dom, forf consom-access, système actif, 1perf/ j, PERFADOM42-C-SA IMMU-IV. Forfait journalier de consommables e', null, 'hebdomadaire', 'perfusion', true),
  ('1153467', 'perfusion — Perf à dom, forf heb consom-access, système actif, 1perf/ S, PERFADOM41-C-SA IMMU-SC. Forfait hebdomadaire de consomma', 49.28, 'hebdomadaire', 'perfusion', true),
  ('1153480', 'nutrition entérale — Nutrition entérale, forfait de première installation. Ce forfait couvre la fourniture du matériel nécessaire', 175.84, 'installation', 'nead', true),
  ('1153616', 'perfusion — Perf à dom, forf hebdo consom-access, Gravité, > 2 perf/ j, PERFADOM20-C-GRAV > 2/ J. Forfait hebdomadaire de consomma', 204.24, 'hebdomadaire', 'perfusion', true),
  ('1154018', 'perfusion — Perf à dom, forf hebdo consom-access, diffuseur, 1 perf/ j, PERFADOM37-C-DIFF = 1/ J. Forfait hebdomadaire de consomma', 216.12, 'hebdomadaire', 'perfusion', true),
  ('1156023', 'perfusion — Perf à dom, forf hebdo consom-access, diffuseur, 1 perf/ s, PERFADOM34-C-DIFF = 1/ S. Forfait hebdomadaire de consomma', null, 'hebdomadaire', 'perfusion', true),
  ('1157318', 'perfusion — Perf à dom, forf hebdo consom-access, débr diff étab sant, PERFADOM24-C-DEBR-DIFF. Forfait de consommables et d''access', 13.80, 'unitaire', 'perfusion', true),
  ('1159062', 'perfusion — Perfusion à domicile, forf instal2, système actif élec, PERFADOM2-I2-SA-ELEC. Forfait de seconde installation de perfu', null, 'installation', 'perfusion', true),
  ('1164778', 'perfusion — Perfusion à domicile, forf instal1, diffuseur, PERFADOM4-I1-DIFF. Forfait de première installation de la perfusion à d', null, 'installation', 'perfusion', true),
  ('1168470', 'perfusion — Perf à dom, forf hebdo consom-access, système actif, 1perf/ s, PERFADOM27-C-SA = 1/ S. Forfait hebdomadaire de consomm', 35.72, 'hebdomadaire', 'perfusion', true),
  ('1169675', 'perfusion — Perf a dom, forf hebdo consom-access, système actif, 2 perf/ j, PERFADOM31-C-SA = 2/ J. Forfait hebdomadaire de consom', 467.59, 'hebdomadaire', 'perfusion', true),
  ('1170419', 'perfusion — Perfusion à dom, forfait d''ent voie centrale, PERFADOM22-ENTRETIEN-VC-PICC-LINE. Forfait de consommables et d''accessoi', 17.86, 'unitaire', 'perfusion', true),
  ('1172619', 'perfusion — Perfusion à domicile, forfait instal et suivi, gravité, PERFADOM6-IS-GRAV. Forfait d''installation et de suivi de la pe', 45.79, 'installation', 'perfusion', true),
  ('1176876', 'nutrition entérale — Nutrition entérale, forfait hebdomadaire avec pompe ou régulateur de débit : Forfait 2, avec pompe ou régulat', 82.23, 'hebdomadaire', 'nead', true),
  ('1176882', 'perfusion — Perfusion à domicile, forf instal1, syst actif électrique, PERFADOM1-I1-SA-ELEC. Forfait de première installation de l', 357.20, 'installation', 'perfusion', true),
  ('1178556', 'perfusion — Perfusion à domicile, forfait hebdo suivi, système actif, PERFADOM7E-S-SA-ELEC. Forfait hebdomadaire de suivi de la pe', null, 'installation', 'perfusion', true),
  ('1179165', 'perfusion — Perfusion à domicile, forfait hebdo suivi, diffuseur, PERFADOM8-S-DIFF. Forfait hebdomadaire de suivi de la perfusion', 45.79, 'hebdomadaire', 'perfusion', true),
  ('1183570', 'perfusion — Perf à dom, forf ins rempli par ES, syst actif élec, PERFADOM3-I-REMPLI-ES-SA-ELEC . Forfait d''installation d''un systè', 164.86, 'installation', 'perfusion', true),
  ('1185160', 'perfusion — Perf à dom, forf/ perf consom-access, Gravité, < 15 perf, PERFADOM17-C-GRAV < 15/ 28J. Forfait, par perfusion, de cons', null, 'unitaire', 'perfusion', true),
  ('1185680', 'nutrition parentérale — Nutrition parentérale 6 ou 7 j/7, consommables et accessoires, forfait. Pour chaque période entamée de 7 j', 190.00, 'hebdomadaire', 'npad', true),
  ('1187489', 'perfusion — Perf a dom, forf hebdo consom-access, système actif, 1 perf/ j, PERFADOM30-C-SA = 1/ J. Forfait hebdomadaire de consom', 246.81, 'hebdomadaire', 'perfusion', true),
  ('1191108', 'perfusion — Perfusion à domicile, forf instal2, diffuseur, PERFADOM5-I2-DIFF. Forfait de seconde installation d''un diffuseur à com', 105.33, 'installation', 'perfusion', true),
  ('1192510', 'nutrition parentérale — Nutrition parentérale < = 5 j/7 avec entérale, pompe(s), prest° hebd, pdt 12 prem sem. Forfait de prestati', 140.00, 'installation', 'npad', true),
  ('1193780', 'nutrition entérale — Nutrition entérale, sonde polyuréthane/silicone, naso-gastrique ou naso-jéjunale. Sonde en polyuréthane ou en', 5.24, 'unitaire', 'nead', true),
  ('1195879', 'perfusion — Perf à dom, forf hebdo consom-access, débr SA étab sant, PERFADOM45-C-DEBR-SA. Forfait de consommables et d’accessoire', 13.80, 'unitaire', 'perfusion', true)
on conflict (code) do update set libelle=excluded.libelle, prix_ttc=coalesce(excluded.prix_ttc, public.lpp.prix_ttc), periodicite=excluded.periodicite, famille=excluded.famille, a_verifier=true;
